version: '3.6'
services:
  web:
    build:
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    container_name: gitlab
    image: 'gitlab/gitlab-ee:latest'
    restart: "${DOCKER_RESTART_POLICY:-always}"
    hostname: '${GITLAB_HOSTNAME}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${GITLAB_HOSTNAME}:${GITLAB_WEB_PORT:-8929}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT:-224}
    ports:
      - '${GITLAB_WEB_PORT:-8929}:8929'
      - '${GITLAB_SSH_PORT:-2224}:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '${GITLAB_SHM_SIZE:-256m}'
